/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Axiom {
    id: string;
    complianceRate: bigint;
    name: string;
    description: string;
    driftDetected: boolean;
}
export interface IntegrityReport {
    axioms: Array<Axiom>;
    overallScore: bigint;
    agents: Array<IntegrityAgent>;
    lastAudit: bigint;
}
export interface KafkaTopic {
    id: string;
    name: string;
    description: string;
    messageCount: bigint;
    throughput: bigint;
}
export interface CostModel {
    cyclesPerHour: bigint;
    gasFeePerTx: bigint;
    storageGB: bigint;
    agentCount: bigint;
    rpcCallsPerHour: bigint;
}
export interface SkillsMatrix {
    agents: Array<AgentCapabilities>;
    sharedSkills: Array<string>;
}
export interface CostEstimate {
    cycleCost: bigint;
    storageCost: bigint;
    rpcCost: bigint;
    totalCostIcp: bigint;
    totalCostUsd: bigint;
    gasCost: bigint;
}
export interface BuildSummary {
    lastUpdated: bigint;
    layerItems: bigint;
    layerDone: bigint;
    majorAreas: bigint;
    majorDone: bigint;
}
export interface KafkaConnection {
    connectionType: TopicRole;
    fromAgent: string;
    toTopic: string;
}
export interface DeploymentConfig {
    lastDeployTime?: bigint;
    environment: string;
    deployedComponents: Array<string>;
    networkId: string;
}
export interface DeployStep {
    status: DeployStepStatus;
    component: string;
    description: string;
    command: string;
    stepNumber: bigint;
    notes?: string;
}
export interface BuildArea {
    id: string;
    status: BuildStatus;
    completionPct: bigint;
    name: string;
    layer: bigint;
}
export interface BuildPipeline {
    areas: Array<BuildArea>;
    summary: BuildSummary;
}
export interface KafkaTopology {
    totalMessages: bigint;
    connections: Array<KafkaConnection>;
    topics: Array<KafkaTopic>;
}
export interface Controls {
    primaryMode: PrimaryMode;
    armed: boolean;
    secondaryMode: SecondaryMode;
}
export interface AgentCapabilities {
    domain: string;
    agentName: string;
    overallRating: bigint;
    skills: Array<AgentSkill>;
}
export interface Config {
    pollingInterval: bigint;
    cpuThreshold: bigint;
    responseDelay: bigint;
    memoryThreshold: bigint;
}
export interface IntegrityAgent {
    lastCalibrated: string;
    status: AgentStatus;
    domain: string;
    axiomDrift: bigint;
    name: string;
    alertLevel: AlertLevel;
    integrityScore: bigint;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface LogEntry {
    action: string;
    oldValue: string;
    newValue: string;
    timestamp: bigint;
}
export interface AgentStatusUpdate {
    agentName: string;
    domain: string;
    status: AgentStatus;
    alertLevel: AlertLevel;
    integrityScore: bigint;
    axiomDrift: bigint;
    lastCalibrated: string;
    cpuLoad?: bigint;
    memoryUsage?: bigint;
    uptime?: bigint;
    source: string;
}
export interface KafkaSignal {
    sourceAgent: string;
    topicId: string;
    topicName: string;
    description: string;
    messageCountDelta: bigint;
    throughput: bigint;
}
export interface AgentSkill {
    name: string;
    level: bigint;
    isShared: boolean;
    category: SkillCategory;
}
export interface Metrics {
    cpuLoad: bigint;
    memoryUsage: bigint;
    uptime: bigint;
    timestamp: bigint;
}
export enum AgentStatus {
    active = "active",
    gated = "gated",
    offline = "offline",
    advisory = "advisory"
}
export enum AlertLevel {
    warning = "warning",
    nominal = "nominal",
    caution = "caution",
    critical = "critical"
}
export enum BuildStatus {
    notStarted = "notStarted",
    done = "done",
    blocked = "blocked",
    partial = "partial"
}
export enum DeployStepStatus {
    pending = "pending",
    skipped = "skipped",
    complete = "complete",
    failed = "failed",
    running = "running"
}
export enum PrimaryMode {
    active = "active",
    standby = "standby",
    diagnostic = "diagnostic"
}
export enum SecondaryMode {
    control = "control",
    optimize = "optimize",
    monitor = "monitor"
}
export enum SkillCategory {
    integration = "integration",
    domain = "domain",
    core = "core",
    integrity = "integrity"
}
export enum TopicRole {
    both = "both",
    publisher = "publisher",
    subscriber = "subscriber"
}
export interface backendInterface {
    estimateCost(model: CostModel): Promise<CostEstimate>;
    getActivityLog(): Promise<Array<LogEntry>>;
    getBuildPipeline(): Promise<BuildPipeline>;
    getConfig(): Promise<Config>;
    getControls(): Promise<Controls>;
    getCostModel(): Promise<CostModel>;
    getDeploymentConfig(): Promise<DeploymentConfig>;
    getDeploymentSteps(): Promise<Array<DeployStep>>;
    getIntegrityReport(): Promise<IntegrityReport>;
    getKafkaTopology(): Promise<KafkaTopology>;
    getMetrics(): Promise<Metrics>;
    getSkillsMatrix(): Promise<SkillsMatrix>;
    pushKafkaSignal(signal: KafkaSignal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    markStepComplete(stepNumber: bigint): Promise<Result>;
    resetDeployment(): Promise<void>;
    setArmed(value: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setPrimaryMode(mode: PrimaryMode): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setSecondaryMode(mode: SecondaryMode): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateAgentStatus(update: AgentStatusUpdate): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateConfig(newCpuThreshold: bigint, newMemThreshold: bigint, newPollingInterval: bigint, newResponseDelay: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateCostModel(model: CostModel): Promise<Result>;
}
import type { AgentCapabilities as _AgentCapabilities, AgentSkill as _AgentSkill, AgentStatus as _AgentStatus, AgentStatusUpdate as _AgentStatusUpdate, AlertLevel as _AlertLevel, Axiom as _Axiom, BuildArea as _BuildArea, BuildPipeline as _BuildPipeline, BuildStatus as _BuildStatus, BuildSummary as _BuildSummary, Controls as _Controls, DeployStep as _DeployStep, DeployStepStatus as _DeployStepStatus, DeploymentConfig as _DeploymentConfig, IntegrityAgent as _IntegrityAgent, IntegrityReport as _IntegrityReport, KafkaConnection as _KafkaConnection, KafkaSignal as _KafkaSignal, KafkaTopic as _KafkaTopic, KafkaTopology as _KafkaTopology, PrimaryMode as _PrimaryMode, Result as _Result, SecondaryMode as _SecondaryMode, SkillCategory as _SkillCategory, SkillsMatrix as _SkillsMatrix, TopicRole as _TopicRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async estimateCost(arg0: CostModel): Promise<CostEstimate> {
        if (this.processError) {
            try {
                const result = await this.actor.estimateCost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.estimateCost(arg0);
            return result;
        }
    }
    async getActivityLog(): Promise<Array<LogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLog();
            return result;
        }
    }
    async getBuildPipeline(): Promise<BuildPipeline> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuildPipeline();
                return from_candid_BuildPipeline_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuildPipeline();
            return from_candid_BuildPipeline_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConfig(): Promise<Config> {
        if (this.processError) {
            try {
                const result = await this.actor.getConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConfig();
            return result;
        }
    }
    async getControls(): Promise<Controls> {
        if (this.processError) {
            try {
                const result = await this.actor.getControls();
                return from_candid_Controls_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getControls();
            return from_candid_Controls_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCostModel(): Promise<CostModel> {
        if (this.processError) {
            try {
                const result = await this.actor.getCostModel();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCostModel();
            return result;
        }
    }
    async getDeploymentConfig(): Promise<DeploymentConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeploymentConfig();
                return from_candid_DeploymentConfig_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeploymentConfig();
            return from_candid_DeploymentConfig_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeploymentSteps(): Promise<Array<DeployStep>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeploymentSteps();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeploymentSteps();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIntegrityReport(): Promise<IntegrityReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getIntegrityReport();
                return from_candid_IntegrityReport_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIntegrityReport();
            return from_candid_IntegrityReport_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKafkaTopology(): Promise<KafkaTopology> {
        if (this.processError) {
            try {
                const result = await this.actor.getKafkaTopology();
                return from_candid_KafkaTopology_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKafkaTopology();
            return from_candid_KafkaTopology_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMetrics(): Promise<Metrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMetrics();
            return result;
        }
    }
    async getSkillsMatrix(): Promise<SkillsMatrix> {
        if (this.processError) {
            try {
                const result = await this.actor.getSkillsMatrix();
                return from_candid_SkillsMatrix_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSkillsMatrix();
            return from_candid_SkillsMatrix_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async pushKafkaSignal(arg0: KafkaSignal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.pushKafkaSignal(arg0);
                return from_candid_variant_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pushKafkaSignal(arg0);
            return from_candid_variant_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async markStepComplete(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.markStepComplete(arg0);
                return from_candid_Result_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markStepComplete(arg0);
            return from_candid_Result_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetDeployment(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetDeployment();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetDeployment();
            return result;
        }
    }
    async setArmed(arg0: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setArmed(arg0);
                return from_candid_variant_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setArmed(arg0);
            return from_candid_variant_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async setPrimaryMode(arg0: PrimaryMode): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setPrimaryMode(to_candid_PrimaryMode_n51(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPrimaryMode(to_candid_PrimaryMode_n51(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async setSecondaryMode(arg0: SecondaryMode): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setSecondaryMode(to_candid_SecondaryMode_n53(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSecondaryMode(to_candid_SecondaryMode_n53(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateConfig(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateConfig(arg0, arg1, arg2, arg3);
                return from_candid_variant_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateConfig(arg0, arg1, arg2, arg3);
            return from_candid_variant_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAgentStatus(arg0: AgentStatusUpdate): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAgentStatus(to_candid_AgentStatusUpdate_n55(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAgentStatus(to_candid_AgentStatusUpdate_n55(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCostModel(arg0: CostModel): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCostModel(arg0);
                return from_candid_Result_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCostModel(arg0);
            return from_candid_Result_n49(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AgentCapabilities_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgentCapabilities): AgentCapabilities {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_AgentSkill_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgentSkill): AgentSkill {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_AgentStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgentStatus): AgentStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_AlertLevel_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertLevel): AlertLevel {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_BuildArea_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BuildArea): BuildArea {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_BuildPipeline_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BuildPipeline): BuildPipeline {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_BuildStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BuildStatus): BuildStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Controls_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Controls): Controls {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_DeployStepStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeployStepStatus): DeployStepStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_DeployStep_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeployStep): DeployStep {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_DeploymentConfig_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeploymentConfig): DeploymentConfig {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_IntegrityAgent_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IntegrityAgent): IntegrityAgent {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_IntegrityReport_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IntegrityReport): IntegrityReport {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_KafkaConnection_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KafkaConnection): KafkaConnection {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_KafkaTopology_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KafkaTopology): KafkaTopology {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_PrimaryMode_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrimaryMode): PrimaryMode {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_SecondaryMode_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SecondaryMode): SecondaryMode {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_SkillCategory_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SkillCategory): SkillCategory {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_SkillsMatrix_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SkillsMatrix): SkillsMatrix {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_TopicRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TopicRole): TopicRole {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastDeployTime: [] | [bigint];
    environment: string;
    deployedComponents: Array<string>;
    networkId: string;
}): {
    lastDeployTime?: bigint;
    environment: string;
    deployedComponents: Array<string>;
    networkId: string;
} {
    return {
        lastDeployTime: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.lastDeployTime)),
        environment: value.environment,
        deployedComponents: value.deployedComponents,
        networkId: value.networkId
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _DeployStepStatus;
    component: string;
    description: string;
    command: string;
    stepNumber: bigint;
    notes: [] | [string];
}): {
    status: DeployStepStatus;
    component: string;
    description: string;
    command: string;
    stepNumber: bigint;
    notes?: string;
} {
    return {
        status: from_candid_DeployStepStatus_n20(_uploadFile, _downloadFile, value.status),
        component: value.component,
        description: value.description,
        command: value.command,
        stepNumber: value.stepNumber,
        notes: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.notes))
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    areas: Array<_BuildArea>;
    summary: _BuildSummary;
}): {
    areas: Array<BuildArea>;
    summary: BuildSummary;
} {
    return {
        areas: from_candid_vec_n3(_uploadFile, _downloadFile, value.areas),
        summary: value.summary
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    axioms: Array<_Axiom>;
    overallScore: bigint;
    agents: Array<_IntegrityAgent>;
    lastAudit: bigint;
}): {
    axioms: Array<Axiom>;
    overallScore: bigint;
    agents: Array<IntegrityAgent>;
    lastAudit: bigint;
} {
    return {
        axioms: value.axioms,
        overallScore: value.overallScore,
        agents: from_candid_vec_n25(_uploadFile, _downloadFile, value.agents),
        lastAudit: value.lastAudit
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastCalibrated: string;
    status: _AgentStatus;
    domain: string;
    axiomDrift: bigint;
    name: string;
    alertLevel: _AlertLevel;
    integrityScore: bigint;
}): {
    lastCalibrated: string;
    status: AgentStatus;
    domain: string;
    axiomDrift: bigint;
    name: string;
    alertLevel: AlertLevel;
    integrityScore: bigint;
} {
    return {
        lastCalibrated: value.lastCalibrated,
        status: from_candid_AgentStatus_n28(_uploadFile, _downloadFile, value.status),
        domain: value.domain,
        axiomDrift: value.axiomDrift,
        name: value.name,
        alertLevel: from_candid_AlertLevel_n30(_uploadFile, _downloadFile, value.alertLevel),
        integrityScore: value.integrityScore
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalMessages: bigint;
    connections: Array<_KafkaConnection>;
    topics: Array<_KafkaTopic>;
}): {
    totalMessages: bigint;
    connections: Array<KafkaConnection>;
    topics: Array<KafkaTopic>;
} {
    return {
        totalMessages: value.totalMessages,
        connections: from_candid_vec_n34(_uploadFile, _downloadFile, value.connections),
        topics: value.topics
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    connectionType: _TopicRole;
    fromAgent: string;
    toTopic: string;
}): {
    connectionType: TopicRole;
    fromAgent: string;
    toTopic: string;
} {
    return {
        connectionType: from_candid_TopicRole_n37(_uploadFile, _downloadFile, value.connectionType),
        fromAgent: value.fromAgent,
        toTopic: value.toTopic
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    agents: Array<_AgentCapabilities>;
    sharedSkills: Array<string>;
}): {
    agents: Array<AgentCapabilities>;
    sharedSkills: Array<string>;
} {
    return {
        agents: from_candid_vec_n41(_uploadFile, _downloadFile, value.agents),
        sharedSkills: value.sharedSkills
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    domain: string;
    agentName: string;
    overallRating: bigint;
    skills: Array<_AgentSkill>;
}): {
    domain: string;
    agentName: string;
    overallRating: bigint;
    skills: Array<AgentSkill>;
} {
    return {
        domain: value.domain,
        agentName: value.agentName,
        overallRating: value.overallRating,
        skills: from_candid_vec_n44(_uploadFile, _downloadFile, value.skills)
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    level: bigint;
    isShared: boolean;
    category: _SkillCategory;
}): {
    name: string;
    level: bigint;
    isShared: boolean;
    category: SkillCategory;
} {
    return {
        name: value.name,
        level: value.level,
        isShared: value.isShared,
        category: from_candid_SkillCategory_n47(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _BuildStatus;
    completionPct: bigint;
    name: string;
    layer: bigint;
}): {
    id: string;
    status: BuildStatus;
    completionPct: bigint;
    name: string;
    layer: bigint;
} {
    return {
        id: value.id,
        status: from_candid_BuildStatus_n6(_uploadFile, _downloadFile, value.status),
        completionPct: value.completionPct,
        name: value.name,
        layer: value.layer
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    primaryMode: _PrimaryMode;
    armed: boolean;
    secondaryMode: _SecondaryMode;
}): {
    primaryMode: PrimaryMode;
    armed: boolean;
    secondaryMode: SecondaryMode;
} {
    return {
        primaryMode: from_candid_PrimaryMode_n10(_uploadFile, _downloadFile, value.primaryMode),
        armed: value.armed,
        secondaryMode: from_candid_SecondaryMode_n12(_uploadFile, _downloadFile, value.secondaryMode)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    standby: null;
} | {
    diagnostic: null;
}): PrimaryMode {
    return "active" in value ? PrimaryMode.active : "standby" in value ? PrimaryMode.standby : "diagnostic" in value ? PrimaryMode.diagnostic : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    control: null;
} | {
    optimize: null;
} | {
    monitor: null;
}): SecondaryMode {
    return "control" in value ? SecondaryMode.control : "optimize" in value ? SecondaryMode.optimize : "monitor" in value ? SecondaryMode.monitor : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    skipped: null;
} | {
    complete: null;
} | {
    failed: null;
} | {
    running: null;
}): DeployStepStatus {
    return "pending" in value ? DeployStepStatus.pending : "skipped" in value ? DeployStepStatus.skipped : "complete" in value ? DeployStepStatus.complete : "failed" in value ? DeployStepStatus.failed : "running" in value ? DeployStepStatus.running : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    gated: null;
} | {
    offline: null;
} | {
    advisory: null;
}): AgentStatus {
    return "active" in value ? AgentStatus.active : "gated" in value ? AgentStatus.gated : "offline" in value ? AgentStatus.offline : "advisory" in value ? AgentStatus.advisory : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    warning: null;
} | {
    nominal: null;
} | {
    caution: null;
} | {
    critical: null;
}): AlertLevel {
    return "warning" in value ? AlertLevel.warning : "nominal" in value ? AlertLevel.nominal : "caution" in value ? AlertLevel.caution : "critical" in value ? AlertLevel.critical : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    both: null;
} | {
    publisher: null;
} | {
    subscriber: null;
}): TopicRole {
    return "both" in value ? TopicRole.both : "publisher" in value ? TopicRole.publisher : "subscriber" in value ? TopicRole.subscriber : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    integration: null;
} | {
    domain: null;
} | {
    core: null;
} | {
    integrity: null;
}): SkillCategory {
    return "integration" in value ? SkillCategory.integration : "domain" in value ? SkillCategory.domain : "core" in value ? SkillCategory.core : "integrity" in value ? SkillCategory.integrity : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notStarted: null;
} | {
    done: null;
} | {
    blocked: null;
} | {
    partial: null;
}): BuildStatus {
    return "notStarted" in value ? BuildStatus.notStarted : "done" in value ? BuildStatus.done : "blocked" in value ? BuildStatus.blocked : "partial" in value ? BuildStatus.partial : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DeployStep>): Array<DeployStep> {
    return value.map((x)=>from_candid_DeployStep_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IntegrityAgent>): Array<IntegrityAgent> {
    return value.map((x)=>from_candid_IntegrityAgent_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BuildArea>): Array<BuildArea> {
    return value.map((x)=>from_candid_BuildArea_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_KafkaConnection>): Array<KafkaConnection> {
    return value.map((x)=>from_candid_KafkaConnection_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AgentCapabilities>): Array<AgentCapabilities> {
    return value.map((x)=>from_candid_AgentCapabilities_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AgentSkill>): Array<AgentSkill> {
    return value.map((x)=>from_candid_AgentSkill_n45(_uploadFile, _downloadFile, x));
}
function to_candid_PrimaryMode_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PrimaryMode): _PrimaryMode {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function to_candid_SecondaryMode_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SecondaryMode): _SecondaryMode {
    return to_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PrimaryMode): {
    active: null;
} | {
    standby: null;
} | {
    diagnostic: null;
} {
    return value == PrimaryMode.active ? {
        active: null
    } : value == PrimaryMode.standby ? {
        standby: null
    } : value == PrimaryMode.diagnostic ? {
        diagnostic: null
    } : value;
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SecondaryMode): {
    control: null;
} | {
    optimize: null;
} | {
    monitor: null;
} {
    return value == SecondaryMode.control ? {
        control: null
    } : value == SecondaryMode.optimize ? {
        optimize: null
    } : value == SecondaryMode.monitor ? {
        monitor: null
    } : value;
}
function to_candid_AgentStatusUpdate_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgentStatusUpdate): _AgentStatusUpdate {
    return {
        agentName: value.agentName,
        domain: value.domain,
        status: to_candid_AgentStatus_n28(_uploadFile, _downloadFile, value.status),
        alertLevel: to_candid_AlertLevel_n30(_uploadFile, _downloadFile, value.alertLevel),
        integrityScore: value.integrityScore,
        axiomDrift: value.axiomDrift,
        lastCalibrated: value.lastCalibrated,
        cpuLoad: value.cpuLoad == null ? [] : [
            value.cpuLoad
        ],
        memoryUsage: value.memoryUsage == null ? [] : [
            value.memoryUsage
        ],
        uptime: value.uptime == null ? [] : [
            value.uptime
        ],
        source: value.source
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
import { mockBackend } from "./mocks/backend";

export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend | backendInterface {
    if (canisterId === "mock" || canisterId === "undefined" || !canisterId) {
        return mockBackend;
    }
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
