/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AgentCapabilities {
  'domain' : string,
  'agentName' : string,
  'overallRating' : bigint,
  'skills' : Array<AgentSkill>,
}
export interface AgentSkill {
  'name' : string,
  'level' : bigint,
  'isShared' : boolean,
  'category' : SkillCategory,
}
export type AgentStatus = { 'active' : null } |
  { 'gated' : null } |
  { 'offline' : null } |
  { 'advisory' : null };
export type AlertLevel = { 'warning' : null } |
  { 'nominal' : null } |
  { 'caution' : null } |
  { 'critical' : null };
export interface Axiom {
  'id' : string,
  'complianceRate' : bigint,
  'name' : string,
  'description' : string,
  'driftDetected' : boolean,
}
export interface BuildArea {
  'id' : string,
  'status' : BuildStatus,
  'completionPct' : bigint,
  'name' : string,
  'layer' : bigint,
}
export interface BuildPipeline {
  'areas' : Array<BuildArea>,
  'summary' : BuildSummary,
}
export type BuildStatus = { 'notStarted' : null } |
  { 'done' : null } |
  { 'blocked' : null } |
  { 'partial' : null };
export interface BuildSummary {
  'lastUpdated' : bigint,
  'layerItems' : bigint,
  'layerDone' : bigint,
  'majorAreas' : bigint,
  'majorDone' : bigint,
}
export interface Config {
  'pollingInterval' : bigint,
  'cpuThreshold' : bigint,
  'responseDelay' : bigint,
  'memoryThreshold' : bigint,
}
export interface Controls {
  'primaryMode' : PrimaryMode,
  'armed' : boolean,
  'secondaryMode' : SecondaryMode,
}
export interface CostEstimate {
  'cycleCost' : bigint,
  'storageCost' : bigint,
  'rpcCost' : bigint,
  'totalCostIcp' : bigint,
  'totalCostUsd' : bigint,
  'gasCost' : bigint,
}
export interface CostModel {
  'cyclesPerHour' : bigint,
  'gasFeePerTx' : bigint,
  'storageGB' : bigint,
  'agentCount' : bigint,
  'rpcCallsPerHour' : bigint,
}
export interface DeployStep {
  'status' : DeployStepStatus,
  'component' : string,
  'description' : string,
  'command' : string,
  'stepNumber' : bigint,
  'notes' : [] | [string],
}
export type DeployStepStatus = { 'pending' : null } |
  { 'skipped' : null } |
  { 'complete' : null } |
  { 'failed' : null } |
  { 'running' : null };
export interface DeploymentConfig {
  'lastDeployTime' : [] | [bigint],
  'environment' : string,
  'deployedComponents' : Array<string>,
  'networkId' : string,
}
export interface IntegrityAgent {
  'lastCalibrated' : string,
  'status' : AgentStatus,
  'domain' : string,
  'axiomDrift' : bigint,
  'name' : string,
  'alertLevel' : AlertLevel,
  'integrityScore' : bigint,
}
export interface IntegrityReport {
  'axioms' : Array<Axiom>,
  'overallScore' : bigint,
  'agents' : Array<IntegrityAgent>,
  'lastAudit' : bigint,
}
export interface KafkaConnection {
  'connectionType' : TopicRole,
  'fromAgent' : string,
  'toTopic' : string,
}
export interface KafkaTopic {
  'id' : string,
  'name' : string,
  'description' : string,
  'messageCount' : bigint,
  'throughput' : bigint,
}
export interface KafkaTopology {
  'totalMessages' : bigint,
  'connections' : Array<KafkaConnection>,
  'topics' : Array<KafkaTopic>,
}
export interface LogEntry {
  'action' : string,
  'oldValue' : string,
  'newValue' : string,
  'timestamp' : bigint,
}
export interface AgentStatusUpdate {
  'agentName' : string,
  'domain' : string,
  'status' : AgentStatus,
  'alertLevel' : AlertLevel,
  'integrityScore' : bigint,
  'axiomDrift' : bigint,
  'lastCalibrated' : string,
  'cpuLoad' : [] | [bigint],
  'memoryUsage' : [] | [bigint],
  'uptime' : [] | [bigint],
  'source' : string,
}
export interface Metrics {
  'cpuLoad' : bigint,
  'memoryUsage' : bigint,
  'uptime' : bigint,
  'timestamp' : bigint,
}
export interface KafkaSignal {
  'sourceAgent' : string,
  'topicId' : string,
  'topicName' : string,
  'description' : string,
  'messageCountDelta' : bigint,
  'throughput' : bigint,
}
export type PrimaryMode = { 'active' : null } |
  { 'standby' : null } |
  { 'diagnostic' : null };
export type Result = { 'ok' : null } |
  { 'err' : string };
export type SecondaryMode = { 'control' : null } |
  { 'optimize' : null } |
  { 'monitor' : null };
export type SkillCategory = { 'integration' : null } |
  { 'domain' : null } |
  { 'core' : null } |
  { 'integrity' : null };
export interface SkillsMatrix {
  'agents' : Array<AgentCapabilities>,
  'sharedSkills' : Array<string>,
}
export type TopicRole = { 'both' : null } |
  { 'publisher' : null } |
  { 'subscriber' : null };
export interface _SERVICE {
  'estimateCost' : ActorMethod<[CostModel], CostEstimate>,
  'getActivityLog' : ActorMethod<[], Array<LogEntry>>,
  'getBuildPipeline' : ActorMethod<[], BuildPipeline>,
  'getConfig' : ActorMethod<[], Config>,
  'getControls' : ActorMethod<[], Controls>,
  'getCostModel' : ActorMethod<[], CostModel>,
  'getDeploymentConfig' : ActorMethod<[], DeploymentConfig>,
  'getDeploymentSteps' : ActorMethod<[], Array<DeployStep>>,
  'getIntegrityReport' : ActorMethod<[], IntegrityReport>,
  'getKafkaTopology' : ActorMethod<[], KafkaTopology>,
  'getMetrics' : ActorMethod<[], Metrics>,
  'getSkillsMatrix' : ActorMethod<[], SkillsMatrix>,
  'pushKafkaSignal' : ActorMethod<[KafkaSignal], { 'ok' : null } | { 'err' : string }>,
  'markStepComplete' : ActorMethod<[bigint], Result>,
  'resetDeployment' : ActorMethod<[], undefined>,
  'setArmed' : ActorMethod<[boolean], { 'ok' : null } | { 'err' : string }>,
  'setPrimaryMode' : ActorMethod<
    [PrimaryMode],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setSecondaryMode' : ActorMethod<
    [SecondaryMode],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateAgentStatus' : ActorMethod<[AgentStatusUpdate], { 'ok' : null } | { 'err' : string }>,
  'updateConfig' : ActorMethod<
    [bigint, bigint, bigint, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateCostModel' : ActorMethod<[CostModel], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
