/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CostModel = IDL.Record({
  'cyclesPerHour' : IDL.Nat,
  'gasFeePerTx' : IDL.Nat,
  'storageGB' : IDL.Nat,
  'agentCount' : IDL.Nat,
  'rpcCallsPerHour' : IDL.Nat,
});
export const CostEstimate = IDL.Record({
  'cycleCost' : IDL.Nat,
  'storageCost' : IDL.Nat,
  'rpcCost' : IDL.Nat,
  'totalCostIcp' : IDL.Nat,
  'totalCostUsd' : IDL.Nat,
  'gasCost' : IDL.Nat,
});
export const LogEntry = IDL.Record({
  'action' : IDL.Text,
  'oldValue' : IDL.Text,
  'newValue' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const BuildStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'done' : IDL.Null,
  'blocked' : IDL.Null,
  'partial' : IDL.Null,
});
export const BuildArea = IDL.Record({
  'id' : IDL.Text,
  'status' : BuildStatus,
  'completionPct' : IDL.Nat,
  'name' : IDL.Text,
  'layer' : IDL.Nat,
});
export const BuildSummary = IDL.Record({
  'lastUpdated' : IDL.Int,
  'layerItems' : IDL.Nat,
  'layerDone' : IDL.Nat,
  'majorAreas' : IDL.Nat,
  'majorDone' : IDL.Nat,
});
export const BuildPipeline = IDL.Record({
  'areas' : IDL.Vec(BuildArea),
  'summary' : BuildSummary,
});
export const Config = IDL.Record({
  'pollingInterval' : IDL.Nat,
  'cpuThreshold' : IDL.Nat,
  'responseDelay' : IDL.Nat,
  'memoryThreshold' : IDL.Nat,
});
export const PrimaryMode = IDL.Variant({
  'active' : IDL.Null,
  'standby' : IDL.Null,
  'diagnostic' : IDL.Null,
});
export const SecondaryMode = IDL.Variant({
  'control' : IDL.Null,
  'optimize' : IDL.Null,
  'monitor' : IDL.Null,
});
export const Controls = IDL.Record({
  'primaryMode' : PrimaryMode,
  'armed' : IDL.Bool,
  'secondaryMode' : SecondaryMode,
});
export const DeploymentConfig = IDL.Record({
  'lastDeployTime' : IDL.Opt(IDL.Int),
  'environment' : IDL.Text,
  'deployedComponents' : IDL.Vec(IDL.Text),
  'networkId' : IDL.Text,
});
export const DeployStepStatus = IDL.Variant({
  'pending' : IDL.Null,
  'skipped' : IDL.Null,
  'complete' : IDL.Null,
  'failed' : IDL.Null,
  'running' : IDL.Null,
});
export const DeployStep = IDL.Record({
  'status' : DeployStepStatus,
  'component' : IDL.Text,
  'description' : IDL.Text,
  'command' : IDL.Text,
  'stepNumber' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
});
export const Axiom = IDL.Record({
  'id' : IDL.Text,
  'complianceRate' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'driftDetected' : IDL.Bool,
});
export const AgentStatus = IDL.Variant({
  'active' : IDL.Null,
  'gated' : IDL.Null,
  'offline' : IDL.Null,
  'advisory' : IDL.Null,
});
export const AlertLevel = IDL.Variant({
  'warning' : IDL.Null,
  'nominal' : IDL.Null,
  'caution' : IDL.Null,
  'critical' : IDL.Null,
});
export const IntegrityAgent = IDL.Record({
  'lastCalibrated' : IDL.Text,
  'status' : AgentStatus,
  'domain' : IDL.Text,
  'axiomDrift' : IDL.Nat,
  'name' : IDL.Text,
  'alertLevel' : AlertLevel,
  'integrityScore' : IDL.Nat,
});
export const IntegrityReport = IDL.Record({
  'axioms' : IDL.Vec(Axiom),
  'overallScore' : IDL.Nat,
  'agents' : IDL.Vec(IntegrityAgent),
  'lastAudit' : IDL.Int,
});
export const TopicRole = IDL.Variant({
  'both' : IDL.Null,
  'publisher' : IDL.Null,
  'subscriber' : IDL.Null,
});
export const KafkaConnection = IDL.Record({
  'connectionType' : TopicRole,
  'fromAgent' : IDL.Text,
  'toTopic' : IDL.Text,
});
export const KafkaTopic = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'messageCount' : IDL.Nat,
  'throughput' : IDL.Nat,
});
export const KafkaTopology = IDL.Record({
  'totalMessages' : IDL.Nat,
  'connections' : IDL.Vec(KafkaConnection),
  'topics' : IDL.Vec(KafkaTopic),
});
export const Metrics = IDL.Record({
  'cpuLoad' : IDL.Nat,
  'memoryUsage' : IDL.Nat,
  'uptime' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const SkillCategory = IDL.Variant({
  'integration' : IDL.Null,
  'domain' : IDL.Null,
  'core' : IDL.Null,
  'integrity' : IDL.Null,
});
export const AgentSkill = IDL.Record({
  'name' : IDL.Text,
  'level' : IDL.Nat,
  'isShared' : IDL.Bool,
  'category' : SkillCategory,
});
export const AgentCapabilities = IDL.Record({
  'domain' : IDL.Text,
  'agentName' : IDL.Text,
  'overallRating' : IDL.Nat,
  'skills' : IDL.Vec(AgentSkill),
});
export const SkillsMatrix = IDL.Record({
  'agents' : IDL.Vec(AgentCapabilities),
  'sharedSkills' : IDL.Vec(IDL.Text),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'estimateCost' : IDL.Func([CostModel], [CostEstimate], ['query']),
  'getActivityLog' : IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
  'getBuildPipeline' : IDL.Func([], [BuildPipeline], ['query']),
  'getConfig' : IDL.Func([], [Config], ['query']),
  'getControls' : IDL.Func([], [Controls], ['query']),
  'getCostModel' : IDL.Func([], [CostModel], ['query']),
  'getDeploymentConfig' : IDL.Func([], [DeploymentConfig], ['query']),
  'getDeploymentSteps' : IDL.Func([], [IDL.Vec(DeployStep)], ['query']),
  'getIntegrityReport' : IDL.Func([], [IntegrityReport], ['query']),
  'getKafkaTopology' : IDL.Func([], [KafkaTopology], ['query']),
  'getMetrics' : IDL.Func([], [Metrics], ['query']),
  'getSkillsMatrix' : IDL.Func([], [SkillsMatrix], ['query']),
  'markStepComplete' : IDL.Func([IDL.Nat], [Result], []),
  'resetDeployment' : IDL.Func([], [], []),
  'setArmed' : IDL.Func(
      [IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setPrimaryMode' : IDL.Func(
      [PrimaryMode],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setSecondaryMode' : IDL.Func(
      [SecondaryMode],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateConfig' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateCostModel' : IDL.Func([CostModel], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CostModel = IDL.Record({
    'cyclesPerHour' : IDL.Nat,
    'gasFeePerTx' : IDL.Nat,
    'storageGB' : IDL.Nat,
    'agentCount' : IDL.Nat,
    'rpcCallsPerHour' : IDL.Nat,
  });
  const CostEstimate = IDL.Record({
    'cycleCost' : IDL.Nat,
    'storageCost' : IDL.Nat,
    'rpcCost' : IDL.Nat,
    'totalCostIcp' : IDL.Nat,
    'totalCostUsd' : IDL.Nat,
    'gasCost' : IDL.Nat,
  });
  const LogEntry = IDL.Record({
    'action' : IDL.Text,
    'oldValue' : IDL.Text,
    'newValue' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const BuildStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'done' : IDL.Null,
    'blocked' : IDL.Null,
    'partial' : IDL.Null,
  });
  const BuildArea = IDL.Record({
    'id' : IDL.Text,
    'status' : BuildStatus,
    'completionPct' : IDL.Nat,
    'name' : IDL.Text,
    'layer' : IDL.Nat,
  });
  const BuildSummary = IDL.Record({
    'lastUpdated' : IDL.Int,
    'layerItems' : IDL.Nat,
    'layerDone' : IDL.Nat,
    'majorAreas' : IDL.Nat,
    'majorDone' : IDL.Nat,
  });
  const BuildPipeline = IDL.Record({
    'areas' : IDL.Vec(BuildArea),
    'summary' : BuildSummary,
  });
  const Config = IDL.Record({
    'pollingInterval' : IDL.Nat,
    'cpuThreshold' : IDL.Nat,
    'responseDelay' : IDL.Nat,
    'memoryThreshold' : IDL.Nat,
  });
  const PrimaryMode = IDL.Variant({
    'active' : IDL.Null,
    'standby' : IDL.Null,
    'diagnostic' : IDL.Null,
  });
  const SecondaryMode = IDL.Variant({
    'control' : IDL.Null,
    'optimize' : IDL.Null,
    'monitor' : IDL.Null,
  });
  const Controls = IDL.Record({
    'primaryMode' : PrimaryMode,
    'armed' : IDL.Bool,
    'secondaryMode' : SecondaryMode,
  });
  const DeploymentConfig = IDL.Record({
    'lastDeployTime' : IDL.Opt(IDL.Int),
    'environment' : IDL.Text,
    'deployedComponents' : IDL.Vec(IDL.Text),
    'networkId' : IDL.Text,
  });
  const DeployStepStatus = IDL.Variant({
    'pending' : IDL.Null,
    'skipped' : IDL.Null,
    'complete' : IDL.Null,
    'failed' : IDL.Null,
    'running' : IDL.Null,
  });
  const DeployStep = IDL.Record({
    'status' : DeployStepStatus,
    'component' : IDL.Text,
    'description' : IDL.Text,
    'command' : IDL.Text,
    'stepNumber' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
  });
  const Axiom = IDL.Record({
    'id' : IDL.Text,
    'complianceRate' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'driftDetected' : IDL.Bool,
  });
  const AgentStatus = IDL.Variant({
    'active' : IDL.Null,
    'gated' : IDL.Null,
    'offline' : IDL.Null,
    'advisory' : IDL.Null,
  });
  const AlertLevel = IDL.Variant({
    'warning' : IDL.Null,
    'nominal' : IDL.Null,
    'caution' : IDL.Null,
    'critical' : IDL.Null,
  });
  const IntegrityAgent = IDL.Record({
    'lastCalibrated' : IDL.Text,
    'status' : AgentStatus,
    'domain' : IDL.Text,
    'axiomDrift' : IDL.Nat,
    'name' : IDL.Text,
    'alertLevel' : AlertLevel,
    'integrityScore' : IDL.Nat,
  });
  const IntegrityReport = IDL.Record({
    'axioms' : IDL.Vec(Axiom),
    'overallScore' : IDL.Nat,
    'agents' : IDL.Vec(IntegrityAgent),
    'lastAudit' : IDL.Int,
  });
  const AgentStatusUpdate = IDL.Record({
    'agentName' : IDL.Text,
    'domain' : IDL.Text,
    'status' : AgentStatus,
    'alertLevel' : AlertLevel,
    'integrityScore' : IDL.Nat,
    'axiomDrift' : IDL.Nat,
    'lastCalibrated' : IDL.Text,
    'cpuLoad' : IDL.Opt(IDL.Nat),
    'memoryUsage' : IDL.Opt(IDL.Nat),
    'uptime' : IDL.Opt(IDL.Nat),
    'source' : IDL.Text,
  });
  const TopicRole = IDL.Variant({
    'both' : IDL.Null,
    'publisher' : IDL.Null,
    'subscriber' : IDL.Null,
  });
  const KafkaConnection = IDL.Record({
    'connectionType' : TopicRole,
    'fromAgent' : IDL.Text,
    'toTopic' : IDL.Text,
  });
  const KafkaTopic = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'messageCount' : IDL.Nat,
    'throughput' : IDL.Nat,
  });
  const KafkaTopology = IDL.Record({
    'totalMessages' : IDL.Nat,
    'connections' : IDL.Vec(KafkaConnection),
    'topics' : IDL.Vec(KafkaTopic),
  });
  const Metrics = IDL.Record({
    'cpuLoad' : IDL.Nat,
    'memoryUsage' : IDL.Nat,
    'uptime' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const KafkaSignal = IDL.Record({
    'sourceAgent' : IDL.Text,
    'topicId' : IDL.Text,
    'topicName' : IDL.Text,
    'description' : IDL.Text,
    'messageCountDelta' : IDL.Nat,
    'throughput' : IDL.Nat,
  });
  const SkillCategory = IDL.Variant({
    'integration' : IDL.Null,
    'domain' : IDL.Null,
    'core' : IDL.Null,
    'integrity' : IDL.Null,
  });
  const AgentSkill = IDL.Record({
    'name' : IDL.Text,
    'level' : IDL.Nat,
    'isShared' : IDL.Bool,
    'category' : SkillCategory,
  });
  const AgentCapabilities = IDL.Record({
    'domain' : IDL.Text,
    'agentName' : IDL.Text,
    'overallRating' : IDL.Nat,
    'skills' : IDL.Vec(AgentSkill),
  });
  const SkillsMatrix = IDL.Record({
    'agents' : IDL.Vec(AgentCapabilities),
    'sharedSkills' : IDL.Vec(IDL.Text),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  
  return IDL.Service({
    'estimateCost' : IDL.Func([CostModel], [CostEstimate], ['query']),
    'getActivityLog' : IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
    'getBuildPipeline' : IDL.Func([], [BuildPipeline], ['query']),
    'getConfig' : IDL.Func([], [Config], ['query']),
    'getControls' : IDL.Func([], [Controls], ['query']),
    'getCostModel' : IDL.Func([], [CostModel], ['query']),
    'getDeploymentConfig' : IDL.Func([], [DeploymentConfig], ['query']),
    'getDeploymentSteps' : IDL.Func([], [IDL.Vec(DeployStep)], ['query']),
    'getIntegrityReport' : IDL.Func([], [IntegrityReport], ['query']),
    'getKafkaTopology' : IDL.Func([], [KafkaTopology], ['query']),
    'getMetrics' : IDL.Func([], [Metrics], ['query']),
    'getSkillsMatrix' : IDL.Func([], [SkillsMatrix], ['query']),
    'pushKafkaSignal' : IDL.Func([KafkaSignal], [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })], []),
    'markStepComplete' : IDL.Func([IDL.Nat], [Result], []),
    'resetDeployment' : IDL.Func([], [], []),
    'setArmed' : IDL.Func(
        [IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setPrimaryMode' : IDL.Func(
        [PrimaryMode],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setSecondaryMode' : IDL.Func(
        [SecondaryMode],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateAgentStatus' : IDL.Func([AgentStatusUpdate], [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })], []),
    'updateConfig' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateCostModel' : IDL.Func([CostModel], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };
