/**
 * FG-1…FG-3 lesson catalog — docs/FG_CURRICULUM.md
 */

import type { LessonDefinition } from '../lessonEngine/types.js';

const HOUR = 60 * 60 * 1000;
/** Default spacing between interleave and transfer inside a lesson (tests may override). */
export const FG_LESSON_DELAY_MS = 100;

export const FG_LESSONS: readonly LessonDefinition[] = [
  // ─── FG-1 ───────────────────────────────────────────────
  {
    id: 'L1.1',
    title: 'What is yield (and what it isn’t)',
    gate: 'fg1',
    deepRule: 'Yield is compensation for risk, illiquidity, or work—not free money',
    surface: 'Simulated pool APY with hidden risk',
    objective: 'Reject free-yield framing; name risk before APY',
    modelExample:
      'Two pools show 40% APY. Pool A had three 30% drawdowns; Pool B had calm history but exit liquidity risk. Higher advertised yield is not safer.',
    retrievePrompt: 'In one sentence: what is yield, and what is it not?',
    selfExplainPrompt: 'Why can two identical APY labels hide different danger?',
    interleavePrompt: 'A “guaranteed return” product appears. What do you check first?',
    transferPrompt: 'Map the same rule to a non-DeFi “too good to be true” savings offer.',
    delayMs: FG_LESSON_DELAY_MS,
    integrityFocus: 'C',
    shaliahOffice: 'coach',
    retrieveKeys: ['risk', 'yield', 'not free', 'free'],
    transferKeys: ['risk', 'guarantee', 'return', 'cost'],
    explainKeys: ['risk', 'drawdown', 'apy', 'liquidity'],
  },
  {
    id: 'L1.2',
    title: 'Time preference & compounding',
    gate: 'fg1',
    deepRule: 'Small consistent growth compounds; impatience has a price',
    surface: 'Paper Growth Capital over seasons',
    objective: 'Prefer coherent long path under constraint',
    modelExample:
      'Path A extracts early for comfort. Path B keeps r=0.20 Growth Capital working four seasons. B’s claim is larger despite less “cash now.”',
    retrievePrompt: 'What does time preference trade off in Growth Capital?',
    selfExplainPrompt: 'Why does locking r at 20% until graduation use time as a teacher?',
    interleavePrompt: 'You need short-term cash. What is the cost of breaking soft commitment early?',
    transferPrompt: 'Apply compounding patience to a crop/storage or apprenticeship time tradeoff.',
    delayMs: FG_LESSON_DELAY_MS,
    integrityFocus: 'P',
    shaliahOffice: 'coach',
    retrieveKeys: ['time', 'compound', 'patience', 'future'],
    transferKeys: ['time', 'wait', 'later', 'cost'],
    explainKeys: ['compound', 'season', 'growth', 'extract'],
  },
  {
    id: 'L1.3',
    title: 'Units, claim, NAV (bank model)',
    gate: 'fg1',
    deepRule: 'You own a claim (units); funds work in a pool (NAV)',
    surface: 'Paper claim statement UI',
    objective: 'Read personal claim vs collective pool correctly',
    modelExample:
      'You hold 100 units. NAV falls 10%. Units stay 100; claim value falls ~10%. Pool assets move; your share count does not vanish.',
    retrievePrompt: 'If NAV drops 10%, what happens to units vs claim value?',
    selfExplainPrompt: 'Explain bank-style tracking: individual amount vs collective funds.',
    interleavePrompt: 'NAV rises 5%. What changed — units or claim value?',
    transferPrompt: 'Explain your claim vs the pool to a peer in plain language.',
    delayMs: FG_LESSON_DELAY_MS,
    integrityFocus: 'N',
    shaliahOffice: 'mirror',
    retrieveKeys: ['units', 'nav', 'claim', 'value'],
    transferKeys: ['claim', 'pool', 'units', 'collective'],
    explainKeys: ['units', 'nav', 'pool', 'individual'],
  },
  {
    id: 'L1.4',
    title: 'DeFi surface: pool risk in-sim',
    gate: 'fg1',
    deepRule: 'Name failure modes before chasing APY',
    surface: 'Sandbox pool chooser',
    objective: 'List risks before selecting a pool',
    modelExample:
      'Liquidity dries up; exit fails at advertised price. Smart-contract and oracle risks also apply. Name them before yield.',
    retrievePrompt: 'Name two risks you check before entering a yield pool.',
    selfExplainPrompt: 'Why is “name risk first” a Learning Constitution move, not just finance trivia?',
    interleavePrompt: 'A pool with lower APY but audited history appears. How do you compare?',
    transferPrompt: 'Apply risk-naming to a different instrument class (lending vs AMM).',
    delayMs: FG_LESSON_DELAY_MS,
    integrityFocus: 'C',
    shaliahOffice: 'coach',
    retrieveKeys: ['risk', 'liquidity', 'contract', 'oracle', 'smart'],
    transferKeys: ['risk', 'lend', 'amm', 'pool'],
    explainKeys: ['risk', 'yield', 'first', 'failure'],
  },
  {
    id: 'L1.5',
    title: 'Non-crypto: commodity / production',
    gate: 'fg1',
    deepRule: 'Scarcity, storage, time, and demand create value outside tokens',
    surface: 'Commodity / production sim',
    objective: 'Transfer wealth logic beyond crypto skins',
    modelExample:
      'Hold grain vs sell now: storage cost vs expected demand. Waiting has a cost—same deep rule as soft commitment.',
    retrievePrompt: 'What is the cost of waiting in a real-economy hold decision?',
    selfExplainPrompt: 'How does this map to Growth Capital soft commitment?',
    interleavePrompt: 'A production cycle needs capital now. What tradeoff do you name?',
    transferPrompt: 'Connect commodity time cost to Growth Capital windows.',
    delayMs: FG_LESSON_DELAY_MS,
    integrityFocus: 'P',
    shaliahOffice: 'coach',
    retrieveKeys: ['cost', 'wait', 'time', 'storage', 'demand'],
    transferKeys: ['growth', 'capital', 'commit', 'window', 'time'],
    explainKeys: ['storage', 'time', 'commit', 'claim'],
  },
  // ─── FG-2 ───────────────────────────────────────────────
  {
    id: 'L2.1',
    title: 'α / β / γ channels',
    gate: 'fg2',
    deepRule: 'G splits private growth, commons, and job rails by design',
    surface: 'Split visualizer 40/35/25',
    objective: 'Justify channel split without pure selfishness',
    modelExample:
      'G routes 40% claim, 35% community pools, 25% job escrow. Maximizing only claim starves seasons and talent rails.',
    retrievePrompt: 'What do alpha, beta, and gamma fund?',
    selfExplainPrompt: 'If everyone maximized only personal claim, what breaks?',
    interleavePrompt: 'A season bounty is paid from P_comm. Who benefits and why?',
    transferPrompt: 'Allocate a mock G and justify without pure private hoarding.',
    delayMs: FG_LESSON_DELAY_MS,
    integrityFocus: 'C',
    shaliahOffice: 'mirror',
    retrieveKeys: ['claim', 'community', 'job', 'escrow', '40', '35', '25'],
    transferKeys: ['claim', 'community', 'commons', 'job'],
    explainKeys: ['commons', 'claim', 'season', 'pool'],
  },
  {
    id: 'L2.2',
    title: 'Drawdown psychology',
    gate: 'fg2',
    deepRule: 'Loss is information; panic and freeze are both failure modes',
    surface: 'Paper NAV drop path',
    objective: 'Self-explain coherent action under loss',
    modelExample:
      'NAV drops 12%. Panic exit at bottom and total freeze both fail. Coherent response: reassess risk tier, keep soft commitment unless hardship.',
    retrievePrompt: 'Name two unhealthy reactions to drawdown.',
    selfExplainPrompt: 'Describe a coherent next action when claim value falls.',
    interleavePrompt: 'Cohort leaderboard pressure hits during a drop. What stays true?',
    transferPrompt: 'Apply drawdown coherence to a Multitude market shock.',
    delayMs: FG_LESSON_DELAY_MS,
    integrityFocus: 'N',
    shaliahOffice: 'coach',
    retrieveKeys: ['panic', 'freeze', 'loss', 'drawdown'],
    transferKeys: ['risk', 'assess', 'commit', 'shock'],
    explainKeys: ['action', 'risk', 'not panic', 'information'],
  },
  {
    id: 'L2.3',
    title: 'Risk tiers & confirmation',
    gate: 'fg2',
    deepRule: 'High-risk requires human confirm; Shaliah proposes only',
    surface: 'Deployment dialog Safe/Standard/High',
    objective: 'Refuse silent autopilot success',
    modelExample:
      'Shaliah proposes High-risk deploy. UI never auto-accepts. Human confirms or refuses with reason. Autopilot path is instant fail.',
    retrievePrompt: 'Who must confirm a high-risk deployment?',
    selfExplainPrompt: 'Why does autopilot success never raise PL or FG proof?',
    interleavePrompt: 'Spot a mock UI that hides confirm. What is wrong?',
    transferPrompt: 'A Multitude job tries to auto-accept. How do you respond?',
    delayMs: FG_LESSON_DELAY_MS,
    integrityFocus: 'NCP',
    shaliahOffice: 'transactional_vehicle',
    retrieveKeys: ['human', 'confirm', 'high', 'risk'],
    transferKeys: ['refuse', 'confirm', 'auto', 'accept'],
    explainKeys: ['autopilot', 'pl', 'judgment', 'atrophy'],
  },
  {
    id: 'L2.4',
    title: 'Liquidity: soft vs hard commit',
    gate: 'fg2',
    deepRule: 'Soft windows + emergency ≠ inaccessible; hard vaults are opt-in',
    surface: 'Liquidity calendar + emergency flow',
    objective: 'Choose liquidity mode for a life goal ethically',
    modelExample:
      'Soft commitment: scheduled windows + hardship path. Hard goal vault: SEED-style lock you choose. Default is not a black hole.',
    retrievePrompt: 'What is the difference between soft commitment and hard goal vault?',
    selfExplainPrompt: 'When is a hard vault helpful vs harmful?',
    interleavePrompt: 'Emergency need arises. What path exists without gaming the pool?',
    transferPrompt: 'Design a hardship request that Integrity would not flag as abuse.',
    delayMs: FG_LESSON_DELAY_MS,
    integrityFocus: 'C',
    shaliahOffice: 'attention_shield',
    retrieveKeys: ['soft', 'hard', 'window', 'emergency', 'vault'],
    transferKeys: ['hardship', 'emergency', 'honest', 'need'],
    explainKeys: ['opt-in', 'inaccessible', 'commit', 'goal'],
  },
  {
    id: 'L2.5',
    title: 'Job escrow & talent capital',
    gate: 'fg2',
    deepRule: 'E_escrow links proven skill (PoC) to work capital',
    surface: 'Paper job-match board',
    objective: 'Connect Seal domains to talent rails',
    modelExample:
      'PoC domain tags unlock escrow-backed micro-work. No fake badge: Integrity-signed transfer required.',
    retrievePrompt: 'What proof does job escrow need from you?',
    selfExplainPrompt: 'How does teach-bridge raise the floor for others (CCM)?',
    interleavePrompt: 'A job demands a domain you have not transferred. What do you do?',
    transferPrompt: 'Help another learner toward one Seal domain (teach-bridge sketch).',
    delayMs: FG_LESSON_DELAY_MS,
    integrityFocus: 'P',
    shaliahOffice: 'extension',
    retrieveKeys: ['proof', 'poc', 'skill', 'integrity', 'seal'],
    transferKeys: ['teach', 'bridge', 'help', 'domain'],
    explainKeys: ['escrow', 'talent', 'proof', 'transfer'],
  },
  // ─── FG-3 ───────────────────────────────────────────────
  {
    id: 'L3.1',
    title: 'What r actually moves',
    gate: 'fg3',
    deepRule: 'G = r·C; r scales Growth Capital from eligible yield only',
    surface: 'Interactive rate calculator (paper)',
    objective: 'Predict claim/commons effects under different r',
    modelExample:
      'Same C for 6 epochs: r=0.05 vs 0.20 vs 0.30. Higher r grows claim and commons faster from eligible C; if C is zero, r does nothing.',
    retrievePrompt: 'What is G in terms of r and C?',
    selfExplainPrompt: 'If C is zero, what does changing r do?',
    interleavePrompt: 'Compare r=0.05 vs r=0.30 on commons funding over a season.',
    transferPrompt: 'Explain r to someone who thinks it is a tax on all life income.',
    delayMs: FG_LESSON_DELAY_MS,
    integrityFocus: 'C',
    shaliahOffice: 'coach',
    retrieveKeys: ['g', 'r', 'c', 'yield', 'eligible'],
    transferKeys: ['eligible', 'ecosystem', 'not all', 'income', 'yield'],
    explainKeys: ['zero', 'nothing', 'eligible', 'c'],
  },
  {
    id: 'L3.2',
    title: 'Floor & ceiling rationale',
    gate: 'fg3',
    deepRule: 'Bounds protect future-self and commons without erasing autonomy',
    surface: 'Policy card 5%–30%',
    objective: 'Defend bounds with mechanism, not slogan',
    modelExample:
      'Everyone at 0% starves the pool. Everyone above ~30% stresses liquidity. Floor 5% and ceiling 30% after FG-3 balance autonomy and institution.',
    retrievePrompt: 'What are the post-graduation floor and ceiling for r?',
    selfExplainPrompt: 'Why is casual r=0 disallowed in v1?',
    interleavePrompt: 'Argue for the floor using mechanism language.',
    transferPrompt: 'Compare pre-grad locked 20% to post-grad bounded choice as commitment design.',
    delayMs: FG_LESSON_DELAY_MS,
    integrityFocus: 'P',
    shaliahOffice: 'mirror',
    retrieveKeys: ['5', '30', 'floor', 'ceiling', '0.05', '0.30'],
    transferKeys: ['commit', 'default', '20', 'choice', 'lock'],
    explainKeys: ['pool', 'commons', 'zero', 'autonomy'],
  },
  {
    id: 'L3.3',
    title: 'Rate-choice simulation',
    gate: 'fg3',
    deepRule: 'Choice is owned; coach debriefs; Shaliah never sets r',
    surface: 'Multi-scenario sim',
    objective: 'Pick r under scenarios with stable reasons',
    modelExample:
      'Volatile C: slightly higher r still only hits eligible yield. Stable C: learner may choose mid-band. Shaliah proposes questions, not the number.',
    retrievePrompt: 'Who is allowed to set r after FG-3?',
    selfExplainPrompt: 'What would make you choose 10% vs 25%?',
    interleavePrompt: 'Refuse a coach “recommendation” that sounds like a decision for you.',
    transferPrompt: 'Pick r for your actual paper claim state and justify.',
    delayMs: FG_LESSON_DELAY_MS,
    integrityFocus: 'NCP',
    shaliahOffice: 'coach',
    retrieveKeys: ['user', 'human', 'i', 'principal', 'me'],
    transferKeys: ['because', 'claim', 'risk', 'goal'],
    explainKeys: ['volatile', 'stable', 'goal', 'floor'],
  },
  {
    id: 'L3.4',
    title: 'Seasonal escalate (opt-in)',
    gate: 'fg3',
    deepRule: 'Auto-escalate is a future-self tool only with consent',
    surface: 'Grow More Next Season toggle',
    objective: 'Accept or refuse escalate with reason',
    modelExample:
      '+1–2 pp per season toward ceiling, only if user confirms. Inertia helps savers; consent preserves will.',
    retrievePrompt: 'Is seasonal escalate automatic without consent?',
    selfExplainPrompt: 'When would you refuse an escalate prompt?',
    interleavePrompt: 'Design a confirm copy that is not dark-pattern.',
    transferPrompt: 'Link escalate to Save-More-Tomorrow style habit without losing sovereignty.',
    delayMs: FG_LESSON_DELAY_MS,
    integrityFocus: 'C',
    shaliahOffice: 'attention_shield',
    retrieveKeys: ['consent', 'opt', 'confirm', 'not automatic', 'user'],
    transferKeys: ['habit', 'consent', 'future', 'will'],
    explainKeys: ['refuse', 'liquidity', 'stress', 'goal'],
  },
] as const;

export function getLesson(id: string): LessonDefinition | undefined {
  return FG_LESSONS.find((l) => l.id === id);
}

export function lessonsForGate(gate: 'fg1' | 'fg2' | 'fg3'): LessonDefinition[] {
  return FG_LESSONS.filter((l) => l.gate === gate);
}

export const FG1_LESSON_IDS = ['L1.1', 'L1.2', 'L1.3', 'L1.4', 'L1.5'] as const;
export const FG2_LESSON_IDS = ['L2.1', 'L2.2', 'L2.3', 'L2.4', 'L2.5'] as const;
export const FG3_LESSON_IDS = ['L3.1', 'L3.2', 'L3.3', 'L3.4'] as const;
