/**
 * Sign-event + payload schema validators (Phase B, Layer 3 codegen).
 *
 * The 5 ajv validators are generated by gen-ttcl-artifacts.mjs from
 * shared/ttcl-specs/sign-events.json (the Sign-event payload schema) + the 4
 * hand-written shared/schemas/*.json payloads. They are build/test-only — the
 * bus keeps its hand-rolled validateIntentionTraceability as the only runtime
 * check (zero-external-runtime-deps invariant preserved).
 *
 * This suite proves the validators actually check something, not just pass
 * everything through: for each event type there is a POSITIVE case (a conforming
 * fixture passes) AND a NEGATIVE case (a deliberately malformed fixture fails,
 * with the ajv error landing on the broken field's instancePath). A validator
 * that always returned true would fail every negative case here. Per the user's
 * explicit Phase B requirement: "Without negative cases, a validator that
 * always returns true would pass all your tests."
 *
 * Fixture strategy:
 *  - ttcl.observation.emitted: factory-derived at test time (makeTriadicObservation
 *    for positive; a mutated copy for negative) so the payload can never drift
 *    from the LOGOC manifold — no static fixture.
 *  - the 4 existing payload types: hand-authored static fixtures under
 *    shared/fixtures/events/ (deterministic, independent of runtime state).
 *  - the signal-event negative uses a non-uuid `id` to prove ajv-formats is
 *    wired (the uuid format keyword is actually enforced).
 */

import { describe, it, expect } from 'vitest';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

import {
  validateTtclObservation,
  validateSignalEvent,
  validateGnosisScore,
  validateDoveSignal,
  validateHeparAuditResult,
} from '@sovereign/types';
import { makeTriadicObservation } from '@sovereign/ttcl';

const here = dirname(fileURLToPath(import.meta.url));
// integration/ → tests/ → monad-ecosystem/ → repo root → shared/fixtures/events
const fixturesDir = resolve(here, '../../../shared/fixtures/events');

async function loadFixture(name: string): Promise<unknown> {
  const raw = await readFile(join(fixturesDir, name), 'utf8');
  return JSON.parse(raw);
}

type ValidateFn = ((data: unknown) => boolean) & { errors?: unknown[] | null };

/** Assert the validator's last run produced an error at exactly `instancePath`.
 *  Proves the validator checked the broken field, not just rejected the object. */
function expectErrorAt(validate: ValidateFn, instancePath: string): void {
  expect(validate.errors, 'validator.errors should be set after a failing call').toBeTruthy();
  const errors = (validate.errors ?? []) as Array<{ instancePath: string; keyword: string }>;
  const hit = errors.some((e) => e.instancePath === instancePath);
  const seen = errors.map((e) => `${e.instancePath}(${e.keyword})`).join(', ');
  expect(
    hit,
    `expected an ajv error at instancePath "${instancePath}"; saw: ${seen}`,
  ).toBe(true);
}

describe('Sign-event + payload schema validators (Phase B)', () => {
  // ── ttcl.observation.emitted (factory-derived; manifold-consistent) ────────
  it('ttcl.observation.emitted: makeTriadicObservation() output conforms (positive)', () => {
    const payload = makeTriadicObservation();
    const ok = validateTtclObservation(payload);
    if (!ok) console.error('ttcl positive errors:', validateTtclObservation.errors);
    expect(ok).toBe(true);
  });

  it('ttcl.observation.emitted: pps > 1.0 is rejected at /pps (negative)', () => {
    const payload = makeTriadicObservation();
    const bad = { ...payload, pps: 1.5 };
    expect(validateTtclObservation(bad)).toBe(false);
    expectErrorAt(validateTtclObservation as ValidateFn, '/pps');
  });

  it('ttcl.observation.emitted: out-of-range sign_class_id is rejected (negative)', () => {
    const payload = makeTriadicObservation();
    const bad = {
      ...payload,
      peirce: { ...payload.peirce, sign_class_id: 999 },
    };
    expect(validateTtclObservation(bad)).toBe(false);
    expectErrorAt(validateTtclObservation as ValidateFn, '/peirce/sign_class_id');
  });

  // ── signal-event envelope (static fixtures) ────────────────────────────────
  it('signal-event: valid envelope conforms (positive)', async () => {
    const fixture = await loadFixture('signal-event.valid.json');
    expect(validateSignalEvent(fixture)).toBe(true);
  });

  it('signal-event: non-uuid id is rejected at /id — proves ajv-formats wired (negative)', async () => {
    const fixture = await loadFixture('signal-event.invalid.json');
    expect(validateSignalEvent(fixture)).toBe(false);
    expectErrorAt(validateSignalEvent as ValidateFn, '/id');
  });

  // ── gnosis.score.computed (static fixtures) ────────────────────────────────
  it('gnosis-score: valid score conforms (positive)', async () => {
    const fixture = await loadFixture('gnosis-score.valid.json');
    expect(validateGnosisScore(fixture)).toBe(true);
  });

  it('gnosis-score: overallScore > 1.0 is rejected at /overallScore (negative)', async () => {
    const fixture = await loadFixture('gnosis-score.invalid.json');
    expect(validateGnosisScore(fixture)).toBe(false);
    expectErrorAt(validateGnosisScore as ValidateFn, '/overallScore');
  });

  // ── dove.signal.tier1 (static fixtures) ────────────────────────────────────
  it('dove-signal: valid tier-1 signal conforms (positive)', async () => {
    const fixture = await loadFixture('dove-signal.valid.json');
    expect(validateDoveSignal(fixture)).toBe(true);
  });

  it('dove-signal: tier=4 is rejected at /tier (negative)', async () => {
    const fixture = await loadFixture('dove-signal.invalid.json');
    expect(validateDoveSignal(fixture)).toBe(false);
    expectErrorAt(validateDoveSignal as ValidateFn, '/tier');
  });

  // ── hepar.audit.completed (static fixtures) ────────────────────────────────
  it('hepar-audit-result: valid audit conforms (positive)', async () => {
    const fixture = await loadFixture('hepar-audit-result.valid.json');
    expect(validateHeparAuditResult(fixture)).toBe(true);
  });

  it('hepar-audit-result: trace missing intentionId is rejected at /trace (negative)', async () => {
    const fixture = await loadFixture('hepar-audit-result.invalid.json');
    expect(validateHeparAuditResult(fixture)).toBe(false);
    expectErrorAt(validateHeparAuditResult as ValidateFn, '/trace');
  });
});